#Load the embedding

x <- read.table("Yeast_CBS_GB_ITS_1seqfor1strain_Species.outLargeVis", skip = 1, sep= " ")
mydata <- data.frame(index=x[,1],coor1=x[,2],coor2=x[,3],coor3 =x[,4]) #3D
x <-mydata[order(mydata$index),]

#Get distance matrix generated by LargeVis based on similarity matrix computed by MLC
m <- data.frame(coor1=x[,2],coor2=x[,3],coor3=x[,4]) #3D
dist <- as.matrix(dist(m))

#look for neighbors based on coordinated computed by LargeVis based on similarity matrix computed by MLC
y<-t(x)
neighborMatrixbyLargeVis = matrix(data=NA,nrow=length(x[,1]), ncol=length(x[,1])) #neightborof 1 is neighbor[1,]
for (i in 1:length(x[,1])) {
  currentrow <- data.frame(index <- y[1,],rowdist <- dist[i,])
  orderedrow <- currentrow[order(currentrow$rowdist),]
  neighborMatrixbyLargeVis[i,] <- orderedrow$index
}

#Load the complete similarity matrix
simfull <- read.table("Yeast_CBS_GB_ITS_1seqfor1strain_Species.sim", sep= " ")

#Get full similarity matrix 
simmatrix <- matrix(data=0,nrow=length(x[,1]), ncol=length(x[,1]))
for (k in 1:length(simfull[,1])) {
  i <-simfull[k,1]
  j <- simfull[k,2]
  if (simmatrix[i,j] < simfull[k,3] ){
    simmatrix[i,j] = simfull[k,3]
    simmatrix[j,i] = simfull[k,3]
  }
}


#look for real neighbors based on similarity matrix 
neighborMatrix = matrix(data=0,nrow=length(x[,1]), ncol=length(simmatrix[,1])) #neightborof 1 is neighbor[1,]
for (i in 1:length(simmatrix[,1])) {
  currentrow <- data.frame(index <- y[1,],rowsim <- simmatrix[i,])
  orderedrow <- currentrow[order(currentrow$rowsim, decreasing=TRUE),]
  j=1
  while (orderedrow[j,2] >0 & j< length(simmatrix[,1]) + 1){
    neighborMatrix[i,j] = orderedrow[j,1]
    j=j+1
  }
}

#compute accuracy, if the similarity is the same then include the next points into the neighbor list
k <- 150
s=0.9914 
trulyneighbor = 0
count =0
for (i in 1:length(x[,1])) {	 
  for (j in 1:min(k,length(x[,1]))){
    neighborindex = neighborMatrix[i,j]
    if (neighborindex==0){
      next
    }
    if (simmatrix[i,neighborindex]<s){
      next
    }
    count = count + 1
    isneighbor=FALSE
    l=1
    while (l<=min(k,length(x[,1])) & isneighbor == FALSE){
      if (neighborindex ==neighborMatrixbyLargeVis[i,l]){
        isneighbor=TRUE
        trulyneighbor = trulyneighbor + 1
      }
      l=l+1
    }
  }
}  
accuracy = trulyneighbor/count